### PR TITLE
implemented bidirectional udp communication with simulator

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
@mcharleb I tested this with a dummy python udp receiver and I was able to send and receive messages. I just added a usleep(10000) in the mainloop but I'm not sure if this is even needed since the udp receive call already blocks.

**Comment by tumbili** [comment]
Update: I made the socket non-blocking now.

**Comment by LorenzMeier** [comment]
I would prefer an asynchronous pattern with blocking IO on the socket and on the topic (using a poll() fds struct with the actuator_output and UDP socket as entries). That avoids introducing aliasing and rate limitations.

**Comment by tumbili** [comment]
@mcharleb Hi Mark. As you see above Lorenz suggested to use a polling approach. I like that but I'm not sure if we can poll both socket file descriptor and uorb-topic file descriptor in one thread since the latter one is a virtual file descriptor in contrast to the former one. Is there a way how to do this? 
We could imagine dividing the polling into two separate threads.

**Comment by mcharleb** [comment]
There is no way to do a single poll from one thread on the different types of handles. Two threads is likely the best approach

**Comment by tumbili** [comment]
Ok thanks, will do that.

**Pull request merged**
