### PR TITLE
topic listener update

### PR DESCRIPTION
**Pull request by tumbili**
Support more data types and only print if fresh data is available (not yet enabled because orb_check() does not work).

### CODE REVIEW

**Comment by tumbili** [comment]
@mcharleb Mark, could you please have a look why the topic_listener.cpp is not autogenerated?
I see the code you have put in the makefile but the file always stays empty after I build.

**Comment by mcharleb** [comment]
It creates the file under the Build directory (where it should). All build
artifacts need to be there.

On my machine I am building
under /home/mcharleb/work/Dronecode/PX4/mcharleb/Firmware so the file is
created at:

./Build/posix_default.build/home/mcharleb/work/Dronecode/PX4/mcharleb/Firmware/src/systemcmds/topic_listener/topic_listener.cpp

**Comment by tumbili** [comment]
@mcharleb Mark, could you merge this please :-)

**Comment by mcharleb** [comment]
Your changes don't apply cleanly. Can you send me a new merge request after
you sync with my branch?

**Pull request closed without merging**
